name: artefactos

on:
  push:
    branches: ["workflows5"]

jobs:
  job1:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: jmoyano/cautious-meme
          ref: main

      - name: "Mi primer steps job1"
        run: gcc main.c -o main

      - uses: actions/upload-artifact@v3
        with:
          name: salida
          path: main
  job2:
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: main
          
      
