name: artefactos

on:
  push:
    branches: ["workflows5"]

jobs:
  job1:
    name: "build"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: jmoyano/cautious-meme
          ref: main

      - name: "Mi primer steps job1"
        run: gcc main.c -o main

      - uses: actions/upload-artifact@v3
        with:
          name: main
          path: main
  job2:
    needs: [ job1 ]
    name: "test"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: main

      - name: "llamando al ls"
        run: ls

      - name: "dar permisos para que pueda correr main"
        run: chmod 777 main
      - name: "correr el programa"
        run: ./main
      - name: "chekeo de la ejecucion"
        run: if [ $? -eq '0' ]; then echo "Exito"; else echo "Error" ; fi

      
