name: tercero

on: 
     push:
            branches: [ "main" ]
            
jobs:
    job1:
           name: 'Mi primer Job del 3er workflow'
           runs-on: ubuntu-latest
           steps:
              - uses: actions/checkout@v3
                with:
                     repository: jmoyano/eati2023
                     ref: main
                     path: ./main
                     
              
              - name: 'Mi primer steps'
                run: cat ./main/message.txt
                
              - uses: actions/checkout@v3
                with:
                     repository: jmoyano/eati2023
                     ref: anotherbranch
                     path: ./anotherbranch
                     
              
              - name: 'Mi 2do steps'
                run: cat ./anotherbranch/message.txt